site_name: Unreal Engine 文档
theme:
  name: material
  language: zh
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
markdown_extensions:
- toc:
    permalink: true
- tables
- admonition
- codehilite
plugins:
- search
- awesome-pages
nav:
- .Net:
  - AppDomain: .Net/AppDomain.md
- C++:
  - C++: C++/C++.md
  - Cherno C++:
    - 02-Header: C++/Cherno C++/02-Header.md
    - 03-Log Class: C++/Cherno C++/03-Log Class.md
    - 04-Initiate: C++/Cherno C++/04-Initiate.md
    - 03-Log Class.assets: []
    - assets: []
- Cmake:
  - JUCECmake: Cmake/JUCECmake.md
- DCC:
  - 3D Max:
    - assets: []
  - Blender:
    - MeshSync: DCC/Blender/MeshSync.md
    - 插件: DCC/Blender/插件.md
    - assets: []
  - Mixamo:
    - assets: []
- Engine:
  - 00-Environment: Engine/00-Environment.md
  - 01-Log: Engine/01-Log.md
  - assets: []
- PureTS:
  - 00 环境搭建: PureTS/00 环境搭建.md
  - assets: []
- TA:
  - 20 - SRP:
    - 01_SRP: TA/20 - SRP/01_SRP.md
    - 02_Draw Calls: TA/20 - SRP/02_Draw Calls.md
    - 03_Directional Lights: TA/20 - SRP/03_Directional Lights.md
    - 04_Directional Shadows: TA/20 - SRP/04_Directional Shadows.md
    - 05_Baked Light: TA/20 - SRP/05_Baked Light.md
    - 06_Shadow Masks: TA/20 - SRP/06_Shadow Masks.md
    - '07_LOD and Reflections ': TA/20 - SRP/07_LOD and Reflections .md
    - 08_ Complex Maps: TA/20 - SRP/08_ Complex Maps.md
    - 09_Point and Spot Lights: TA/20 - SRP/09_Point and Spot Lights.md
    - 10_Point and Spot Shadows: TA/20 - SRP/10_Point and Spot Shadows.md
    - 11_Post Processing: TA/20 - SRP/11_Post Processing.md
    - 12_HDR: TA/20 - SRP/12_HDR.md
    - 13_Color Grading: TA/20 - SRP/13_Color Grading.md
    - 14_Multiple Cameras: TA/20 - SRP/14_Multiple Cameras.md
    - 15_Particles: TA/20 - SRP/15_Particles.md
    - 16_Render Scale: TA/20 - SRP/16_Render Scale.md
    - 17_FXAA: TA/20 - SRP/17_FXAA.md
    - 架构: TA/20 - SRP/架构.md
  - 20 - URP:
    - 00_调试: TA/20 - URP/00_调试.md
    - 01_URP薄膜干涉: TA/20 - URP/01_URP薄膜干涉.md
    - 22 - RenderFearture: TA/20 - URP/22 - RenderFearture.md
    - Depth: TA/20 - URP/Depth.md
  - 22 - SRP:
    - 00_Modernization: TA/22 - SRP/00_Modernization.md
    - 01_Render Graph: TA/22 - SRP/01_Render Graph.md
    - 02_Renderer Lists: TA/22 - SRP/02_Renderer Lists.md
    - 03_Camera Textures: TA/22 - SRP/03_Camera Textures.md
    - 04_Shadow Textures: TA/22 - SRP/04_Shadow Textures.md
    - 05_Post FX Passes and Textures: TA/22 - SRP/05_Post FX Passes and Textures.md
    - assets: []
  - 22 - URP:
    - 00_缓冲: TA/22 - URP/00_缓冲.md
    - Code: TA/22 - URP/Code.md
    - DownSample: TA/22 - URP/DownSample.md
    - RenderFeature: TA/22 - URP/RenderFeature.md
    - Renderer Objects: TA/22 - URP/Renderer Objects.md
    - aa: TA/22 - URP/aa.md
    - 备注: TA/22 - URP/备注.md
    - 开图片: TA/22 - URP/开图片.md
    - assets: []
  - ComputerShader:
    - 一、简介: TA/ComputerShader/一、简介.md
    - assets: []
  - RenderGraph:
    - RenderGraph思维导图Part0: TA/RenderGraph/RenderGraph思维导图Part0.md
    - RenderGraph思维导图part1: TA/RenderGraph/RenderGraph思维导图part1.md
  - Taecg: []
  - 一些效果:
    - HierarchyWindow: TA/一些效果/HierarchyWindow.md
    - Parallax Mapping（视差映射）: TA/一些效果/Parallax Mapping（视差映射）.md
  - 优化:
    - RTR4: TA/优化/RTR4.md
    - assets: []
  - 屏幕空间:
    - 次表面散射: TA/屏幕空间/次表面散射.md
  - 管线API:
    - MRT: TA/管线API/MRT.md
    - Shadow: TA/管线API/Shadow.md
  - 过程: []
- UE:
  - UE学习路径: UE/UE学习路径.md
  - 源码构建: UE/源码构建.md
  - 4.27Materia:
    - '00': UE/4.27Materia/00.md
    - assets: []
  - assets: []
  - Module:
    - 'Module ': UE/Module/Module .md
  - 渲染:
    - 00 - UE5.4 Shading Model: UE/渲染/00 - UE5.4 Shading Model.md
    - 01 - MeshDrawPass: UE/渲染/01 - MeshDrawPass.md
    - .vs:
      - 渲染:
        - FileContentIndex: []
        - v17: []
    - assets: []
    - 材质蓝图:
      - assets: []
  - 逆向:
    - RenderDoc: UE/逆向/RenderDoc.md
    - RenderDoc抓帧: UE/逆向/RenderDoc抓帧.md
    - Umodel: UE/逆向/Umodel.md
    - assets: []
- Unity:
  - UI Tookit:
    - Edge: Unity/UI Tookit/Edge.md
    - Graph View: Unity/UI Tookit/Graph View.md
    - 程序集: Unity/UI Tookit/程序集.md
    - 端口数据: Unity/UI Tookit/端口数据.md
    - 18 - GraphView:
      - 00 - Setup: Unity/UI Tookit/18 - GraphView/00 - Setup.md
      - assets: []
    - 19 - GraphView:
      - 00 - Start: Unity/UI Tookit/19 - GraphView/00 - Start.md
      - assets: []
    - 20 - GraphView:
      - 00 - Stra: Unity/UI Tookit/20 - GraphView/00 - Stra.md
      - 01 - Save Load: Unity/UI Tookit/20 - GraphView/01 - Save Load.md
      - assets: []
    - 21 - GraphView:
      - Start: Unity/UI Tookit/21 - GraphView/Start.md
      - assets: []
    - 22 - GraphView:
      - 00 - Start: Unity/UI Tookit/22 - GraphView/00 - Start.md
      - assets: []
    - assets: []
    - BTree:
      - BTTree: Unity/UI Tookit/BTree/BTTree.md
    - CodeGraph:
      - 01-改进: Unity/UI Tookit/CodeGraph/01-改进.md
      - CodeGraph: Unity/UI Tookit/CodeGraph/CodeGraph.md
      - assets: []
  - 客户端:
    - 00-serialise: Unity/客户端/00-serialise.md
    - 01-Cinemachine: Unity/客户端/01-Cinemachine.md
    - 02-Delegates、Event: Unity/客户端/02-Delegates、Event.md
    - 03-Action、UnityEvent: Unity/客户端/03-Action、UnityEvent.md
    - 99-电子书: Unity/客户端/99-电子书.md
    - 单例: Unity/客户端/单例.md
    - 程序集: Unity/客户端/程序集.md
    - 行为树: Unity/客户端/行为树.md
  - 工具向:
    - 00-Path: Unity/工具向/00-Path.md
    - Preview: Unity/工具向/Preview.md
    - Ref: Unity/工具向/Ref.md
    - Untitled 1: Unity/工具向/Untitled 1.md
    - 程序集定义: Unity/工具向/程序集定义.md
    - assets: []
    - Editor:
      - 00-Start: Unity/工具向/Editor/00-Start.md
      - 01-Editor: Unity/工具向/Editor/01-Editor.md
      - 02-面板: Unity/工具向/Editor/02-面板.md
      - 03-脏标记: Unity/工具向/Editor/03-脏标记.md
      - 值: Unity/工具向/Editor/值.md
      - assets: []
    - Game Creator 2:
      - assets: []
      - Custom Node:
        - 00-Custom: Unity/工具向/Game Creator 2/Custom Node/00-Custom.md
        - 01-Event: Unity/工具向/Game Creator 2/Custom Node/01-Event.md
        - assets: []
    - Odin:
      - 00-Start: Unity/工具向/Odin/00-Start.md
      - 01-Inspector: Unity/工具向/Odin/01-Inspector.md
      - 02-OdinWindowTest: Unity/工具向/Odin/02-OdinWindowTest.md
      - assets: []
    - Property Drawer:
      - '2022': Unity/工具向/Property Drawer/2022.md
    - Up - Indie Wafflus:
      - Resources Folder:
        - 01 - Requirements: Unity/工具向/Up - Indie Wafflus/Resources Folder/01 - Requirements.md
      - UI Elements:
        - 00_UI Elements: Unity/工具向/Up - Indie Wafflus/UI Elements/00_UI Elements.md
        - 01 - Style Sheet: Unity/工具向/Up - Indie Wafflus/UI Elements/01 - Style Sheet.md
        - assets: []
    - 服务:
      - 服务器: Unity/工具向/服务/服务器.md
    - 相机:
      - Game与Sence同步: Unity/工具向/相机/Game与Sence同步.md
      - 测量工具: Unity/工具向/相机/测量工具.md
      - assets: []
    - 资源管理:
      - Resources Folder: Unity/工具向/资源管理/Resources Folder.md
      - 捕捉设备: Unity/工具向/资源管理/捕捉设备.md
  - 数据结构:
    - Octrees and A: Unity/数据结构/Octrees and A.md
  - 源代码生成器:
    - 一、创建项目: Unity/源代码生成器/一、创建项目.md
    - 资料: Unity/源代码生成器/资料.md
    - assets: []
- Vulkan:
  - 00_Environment: Vulkan/00_Environment.md
  - 00_Environment.assets: []
- 技术音频:
  - 3D Audio: 技术音频/3D Audio.md
  - Ambisonics: 技术音频/Ambisonics.md
  - Plugin: 技术音频/Plugin.md
  - 杜比音效: 技术音频/杜比音效.md
  - assets: []
  - HRTF:
    - 'Ambisonics ': 技术音频/HRTF/Ambisonics .md
    - HRTF: 技术音频/HRTF/HRTF.md
  - Steam Audio:
    - Steam Audio: 技术音频/Steam Audio/Steam Audio.md
  - VST:
    - Vital VST: 技术音频/VST/Vital VST.md
  - Wappi:
    - Wappi: 技术音频/Wappi/Wappi.md
  - Wwise:
    - Wwise空间音频: 技术音频/Wwise/Wwise空间音频.md
    - assets: []
    - WWise C++:
      - WWise-Plugin: 技术音频/Wwise/WWise C++/WWise-Plugin.md
      - assets: []
    - WwisePython:
      - Python: 技术音频/Wwise/WwisePython/Python.md
    - WwiseUE:
      - 可视化: 技术音频/Wwise/WwiseUE/可视化.md
      - assets: []
    - WwiseWindow:
      - WwiseWindow: 技术音频/Wwise/WwiseWindow/WwiseWindow.md
  - 技术音频:
    - Base Kownlagede:
      - assets: []
    - JUCE:
      - 00 - 环境: 技术音频/技术音频/JUCE/00 - 环境.md
      - AkashMurthy:
        - 00- Levelmeters: 技术音频/技术音频/JUCE/AkashMurthy/00- Levelmeters.md
        - assets: []
      - assets: []
      - kash Murthy: []
    - Pure Data:
      - Document: 技术音频/技术音频/Pure Data/Document.md
      - PureData: 技术音频/技术音频/Pure Data/PureData.md
      - Wwise: 技术音频/技术音频/Pure Data/Wwise.md
      - QCGinteractive:
        - Learn: 技术音频/技术音频/Pure Data/QCGinteractive/Learn.md
        - assets: []
      - 緒方匠:
        - たくみ　おがた: 技术音频/技术音频/Pure Data/緒方匠/たくみ　おがた.md
        - assets: []
    - WAV:
      - assets: []
  - 游戏音频分析:
    - Arena Breakout: 技术音频/游戏音频分析/Arena Breakout.md
    - Call Of Duty: 技术音频/游戏音频分析/Call Of Duty.md
    - Escape from Tarkov: 技术音频/游戏音频分析/Escape from Tarkov.md
    - OW: 技术音频/游戏音频分析/OW.md
    - Spider-Man 2: 技术音频/游戏音频分析/Spider-Man 2.md
    - assets: []
    - Wwise:
      - HDR: 技术音频/游戏音频分析/Wwise/HDR.md
      - Wwise: 技术音频/游戏音频分析/Wwise/Wwise.md
  - 音频分析:
    - Cod: 技术音频/音频分析/Cod.md
    - Untitled: 技术音频/音频分析/Untitled.md
    - assets: []
- 辅助类:
  - Github: 辅助类/Github.md
  - assets: []
- 逆向:
  - CSGO: 逆向/CSGO.md
  - Snapdragon Profiler: 逆向/Snapdragon Profiler.md
  - assets: []
- 面试:
  - 心动: 面试/心动.md
  - 技术音频: 面试/技术音频.md
  - assets: []
