name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate Sphinx documentation
        run: |
          cd Python
          python -c "
          import sys
          sys.path.insert(0, '.')
          from SphinxTools import generate_sphinx_docs
          ok, msg = generate_sphinx_docs()
          print(f'生成结果: {ok}, {msg}')
          if not ok:
              sys.exit(1)
          "
          
      - name: Build Sphinx HTML
        run: |
          cd Python
          python -c "
          import sys
          sys.path.insert(0, '.')
          from SphinxTools import build_sphinx_html
          ok, msg = build_sphinx_html()
          print(f'构建结果: {ok}, {msg}')
          if not ok:
              sys.exit(1)
          "
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sphinx_site/_build/html
          force_orphan: true 