name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate Sphinx documentation
        run: |
          cd Python
          python -c "
          import sys
          sys.path.insert(0, '.')
          from SphinxTools import generate_sphinx_docs
          ok, msg = generate_sphinx_docs()
          print(f'Generate result: {ok}, {msg}')
          if not ok:
              sys.exit(1)
          "
          
      - name: Build Sphinx HTML
        run: |
          cd Python
          python -c "
          import sys
          sys.path.insert(0, '.')
          from SphinxTools import build_sphinx_html
          ok, msg = build_sphinx_html()
          print(f'Build result: {ok}, {msg}')
          if not ok:
              sys.exit(1)
          "
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './sphinx_site/_build/html'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 